/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;

import java.util.Scanner;

/**
 *
 * @author RandyNguyen
 */
public class RMS_GUI extends javax.swing.JFrame {

    /**
     * Creates new form RMS_GUI
     */
    public RMS_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws NullPointerException {

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RMS_GUI().setVisible(true);
//            }
//        });
        AuthorizedUser au = new AuthorizedUser();
        au.addAuthUser("Randy", "1234");
        au.addAuthUser("Gareth", "4567");
        au.addAuthUser("Andrew", "7890");
        
        //checks users have been added
        au.printLogins();
        
            boolean isLoggedIn = false;

            while (!isLoggedIn) {
                System.out.print("Username: ");
                Scanner scanner = new Scanner(System.in);
                String UsernameTextField = scanner.nextLine();
                System.out.print("Pin: ");
                String PinTextField = scanner.nextLine();

                //just a test to see if login is for authorized user, admin, or neither
                //in actual GUI it will let the user access the system based on there authorization
                if (au.IsUserAuthorized(UsernameTextField, PinTextField)) {
                    System.out.println(UsernameTextField + " is logged in as an authorized user.");
                    isLoggedIn = true;
                } else {
                    System.out.println("You have entered an incorrect login. Please try again. Note: Login is case sensitive.");
                }
            }
        }
    }

// Variables declaration - do not modify
// End of variables declaration

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
